name: main
on:
  - pull_request
  - push
jobs:
  small:
    name: test / ${{matrix.os}} / ${{matrix.node}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test-api
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        node:
          - 'latest'

  full:
    name: full build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
      - uses: codecov/codecov-action@v2
        with:
            files: ./coverage/lcov.info
            fail_ci_if_error: true
            verbose: true
